<?php
require_once __DIR__ . '/config/auth.php';
require_once __DIR__ . '/config/storage.php';

$user = require_login();

$id = filter_var(
    $_GET['id'] ?? '',
    FILTER_VALIDATE_INT,
    ['options' => ['min_range' => 1]]
);

if ($id === false) {
    http_response_code(400);
    exit('Invalid material ID.');
}

$stmt = $pdo->prepare(
    'SELECT id, original_name, stored_name, status
     FROM materials WHERE id = ?'
);
$stmt->execute([$id]);
$material = $stmt->fetch();

if (!$material) {
    http_response_code(404);
    exit('Material not found.');
}

if (
    $user['role'] !== 'admin'
    && $material['status'] !== 'approved'
) {
    http_response_code(403);
    exit('This material is not approved for download.');
}

// Accept only filenames generated by our upload page.
if (!preg_match('/\A[a-f0-9]{48}\.pdf\z/', $material['stored_name'])) {
    http_response_code(500);
    exit('Invalid stored file.');
}

$path = rtrim($storageDirectory, '/\\')
    . '/' . $material['stored_name'];

if (!is_file($path) || !is_readable($path)) {
    http_response_code(404);
    exit('The PDF file is unavailable. Please contact an admin.');
}

$handle = fopen($path, 'rb');

if ($handle === false) {
    http_response_code(500);
    exit('Unable to open the PDF.');
}

$fileInfo = fstat($handle);

// Record student download requests, excluding admin reviews.
if ($user['role'] === 'student') {
    try {
        $log = $pdo->prepare(
            'INSERT INTO material_downloads (material_id, user_id)
             VALUES (?, ?)'
        );
        $log->execute([$id, $user['id']]);
    } catch (PDOException $e) {
        // A reporting failure should not prevent the download.
        error_log('Download logging failed: ' . $e->getMessage());
    }
}

// Release the session lock while the download runs.
session_write_close();

header('Content-Type: application/pdf');
header('X-Content-Type-Options: nosniff');
header('Cache-Control: private, no-store');
header(
    'Content-Disposition: attachment; filename="material-' . $id
    . '.pdf"; filename*=UTF-8\'\''
    . rawurlencode($material['original_name'])
);

if ($fileInfo !== false) {
    header('Content-Length: ' . $fileInfo['size']);
}

fpassthru($handle);
fclose($handle);
exit;